version: 0.2
phases:
  install:
    commands:
      - echo Setup environment...
      - export CODEBUILD_GIT_TAG="$(git describe --tags --exact-match 2>/dev/null)"
  pre_build:
    commands:
      - echo logging in to ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker pull 758272223864.dkr.ecr.us-east-1.amazonaws.com/git-release-notes:master
  build:
    commands:
      - echo build Docker image git-release-notes:${CODEBUILD_GIT_TAG}
      - docker build --build-arg NPM_TOKEN=${NPM_TOKEN} --cache-from 758272223864.dkr.ecr.us-east-1.amazonaws.com/git-release-notes:master -t git-release-notes:${CODEBUILD_GIT_TAG} .
      - docker tag git-release-notes:${CODEBUILD_GIT_TAG} 758272223864.dkr.ecr.us-east-1.amazonaws.com/git-release-notes:${CODEBUILD_GIT_TAG}
      - echo build Docker image git-release-notes:${CODEBUILD_GIT_TAG} complete `date`
  post_build:
    commands:
      - echo build Docker images complete `date`
      - echo push Docker images to ECR...
      - docker run -e "NPM_TOKEN=${NPM_TOKEN}" 758272223864.dkr.ecr.us-east-1.amazonaws.com/git-release-notes:${CODEBUILD_GIT_TAG} bash -c "npm --no-git-tag-version version v${CODEBUILD_GIT_TAG} && npm publish --tag v${CODEBUILD_GIT_TAG}"
      - docker push 758272223864.dkr.ecr.us-east-1.amazonaws.com/git-release-notes:${CODEBUILD_GIT_TAG}